/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.UIManager;

/**
 *
 * @author juanp
 */
public class VistaBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public VistaBienvenida() {
        
        initComponents();
        setIconImage(getIconImage()); 
    }
    

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Fondos/IconoVentana2.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdmin = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmin.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnAdmin.setText("ADMIN");
        btnAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 100, -1));

        btnUsuario.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnUsuario.setText("USER");
        btnUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        getContentPane().add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 100, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setText("Seleccione su Rol");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 270, 40));

        txtFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Icono3.jpg"))); // NOI18N
        txtFondo.setOpaque(true);
        txtFondo.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(txtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, -20, 850, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdmin;
    public javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtFondo;
    // End of variables declaration//GEN-END:variables
   public void error(String txt){
       JOptionPane.showMessageDialog(null, txt, "Error",JOptionPane.ERROR_MESSAGE);
   }

   public void errorConsola(String txt){
       System.out.print(txt);
   }
    public void msg(String txt){
       JOptionPane.showMessageDialog(null, txt, "Eliminada",JOptionPane.INFORMATION_MESSAGE);
   }  
    public String capturar(String txt) {
        // Crear un campo de contraseña para la entrada
        JPasswordField campoContrasena = new JPasswordField();

        // Mostrar ventana de entrada de contraseña
        int opcion = JOptionPane.showConfirmDialog(null, campoContrasena, txt, JOptionPane.OK_CANCEL_OPTION, JOptionPane.OK_CANCEL_OPTION);

        // Validar la entrada de la contraseña
        if (opcion == JOptionPane.OK_OPTION) {
            // Obtener la contraseña ingresada como un char array
            char[] contrasenaCharArray = campoContrasena.getPassword();

            // Convertir el char array a String (puedes realizar acciones adicionales aquí según tus necesidades)
            return new String(contrasenaCharArray);
        } else {
            // El usuario canceló la entrada de la contraseña
            return null;
        }
    }
}
