package Vista.Clientes;

import javax.swing.JPanel;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

public class VistaComprar extends javax.swing.JFrame {

    public VistaComprar() {
        initComponents();
        SpinnerNumberModel nm= new SpinnerNumberModel();
        nm.setMinimum(0);
        this.spnCantidad.setModel(nm);
        setIconImage(getIconImage()); 
    }
    

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Fondos/IconoVentana2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboxTipo = new javax.swing.JComboBox<>();
        btnAñadirCarrito = new javax.swing.JButton();
        btnSeleccionarProducto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        comboxProductosTipo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        btnSeleccionarTipo = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        txtFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboxTipo.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        comboxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxTipoItemStateChanged(evt);
            }
        });
        comboxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxTipoActionPerformed(evt);
            }
        });
        getContentPane().add(comboxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));

        btnAñadirCarrito.setBackground(new java.awt.Color(153, 153, 153));
        btnAñadirCarrito.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAñadirCarrito.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirCarrito.setText("Añadir al Carrito");
        btnAñadirCarrito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAñadirCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAñadirCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 170, -1));

        btnSeleccionarProducto.setBackground(new java.awt.Color(153, 153, 153));
        btnSeleccionarProducto.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        btnSeleccionarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarProducto.setText("Seleccionar");
        btnSeleccionarProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeleccionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        btnVolver.setBackground(new java.awt.Color(153, 153, 153));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/volver.png"))); // NOI18N
        btnVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 250, -1));

        txtBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(51, 51, 51));
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 590, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("COMPRAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Descripcion");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        txtPais.setEditable(false);
        txtPais.setBackground(new java.awt.Color(255, 255, 255));
        txtPais.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        txtPais.setForeground(new java.awt.Color(51, 51, 51));
        txtPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisActionPerformed(evt);
            }
        });
        getContentPane().add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 250, -1));

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Fabricante");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        txtFabricante.setEditable(false);
        txtFabricante.setBackground(new java.awt.Color(255, 255, 255));
        txtFabricante.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        txtFabricante.setForeground(new java.awt.Color(51, 51, 51));
        txtFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFabricanteActionPerformed(evt);
            }
        });
        getContentPane().add(txtFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 250, -1));

        txtDescripcion.setEditable(false);
        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 2, 12)); // NOI18N
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 250, 130));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Pais");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        btnCarrito.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnCarrito.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/iconoCarrito.png"))); // NOI18N
        btnCarrito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        btnCarrito.setBorderPainted(false);
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarrito.setOpaque(true);
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 60, 50));

        comboxProductosTipo.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        comboxProductosTipo.setForeground(new java.awt.Color(51, 51, 51));
        comboxProductosTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxProductosTipoItemStateChanged(evt);
            }
        });
        comboxProductosTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxProductosTipoActionPerformed(evt);
            }
        });
        getContentPane().add(comboxProductosTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 130, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Precio");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));
        getContentPane().add(spnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, -1));

        btnSeleccionarTipo.setBackground(new java.awt.Color(153, 153, 153));
        btnSeleccionarTipo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        btnSeleccionarTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarTipo.setText("Seleccionar");
        btnSeleccionarTipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeleccionarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarTipoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, -1));

        btnBuscar1.setBackground(new java.awt.Color(153, 153, 153));
        btnBuscar1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar1.setText("Buscar");
        btnBuscar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 70, 30));

        txtFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Icono2.png"))); // NOI18N
        getContentPane().add(txtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -260, 880, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxTipoActionPerformed

    private void btnSeleccionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarProductoActionPerformed

    private void comboxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxTipoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxTipoItemStateChanged

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAñadirCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirCarritoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFabricanteActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void comboxProductosTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxProductosTipoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxProductosTipoItemStateChanged

    private void comboxProductosTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxProductosTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxProductosTipoActionPerformed

    private void btnSeleccionarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarTipoActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAñadirCarrito;
    public javax.swing.JButton btnBuscar1;
    public javax.swing.JButton btnCarrito;
    public javax.swing.JButton btnSeleccionarProducto;
    public javax.swing.JButton btnSeleccionarTipo;
    public javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> comboxProductosTipo;
    public javax.swing.JComboBox<String> comboxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSpinner spnCantidad;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JTextField txtFabricante;
    private javax.swing.JLabel txtFondo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPais;
    public javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    public void error(String txt) {
        JOptionPane.showMessageDialog(null, txt, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void errorConsola(String txt) {
        System.out.print(txt);
    }

    public void msg(String txt) {
        JOptionPane.showMessageDialog(null, txt, "Eliminada", JOptionPane.INFORMATION_MESSAGE);
    }

    public void limpiar() {//Acción boton limpiar
        txtNombre.setText("");
        txtPrecio.setText("");
        txtDescripcion.setText("");
        txtFabricante.setText("");
        txtPais.setText("");
    }

    public String capturar(String txt) {
        return (JOptionPane.showInputDialog(txt));
    }

}
